### ISSUE TITLE
problem with clout edges

### ISSUE THREAD

**Issue by enricorusso** [tliron/puccini#37]
Hello,
the attached zip ([test.zip](https://github.com/tliron/puccini/files/5113854/test.zip)) contains a Tosca blueprint (_tosca.yaml_) and the corresponding compiled clout graph (_puccini.html_) created with _visualize.js_.

As you can see, some clout edges point to wrong nodes: A has two host edges pointing to compute1 and B has the dependency edge pointing to A. 

Please, could you clarify whether this problem is related to the Tosca YAML or the compiled clout?

Thank you
Enrico

puccini version:
```
version=v0.14.0
revision=81e61596c97cfcd9ec3a90331f7bcadc6858aeee
timestamp=2020-05-03 10:07:39 CDT
arch=amd64
os=linux
compiler=gc
```

**Comment by tliron** [comment]
Thank you for the bug report! This has actually been fixed on master a while ago, so it has prompted me to do a new release...

Could you confirm that it is fixed in [v0.15.0](https://github.com/tliron/puccini/releases/tag/v0.15.0)?

**Comment by enricorusso** [comment]
I've just tested the new version with the same test blueprint and others, but the problem still seems to be present...

**Comment by tliron** [comment]
Hi @enricorusso , could you test my fix on master branch?

The bug was that the node type in the requirement definition was being preferred over the node template name in the assignment.

**Comment by enricorusso** [comment]
I confirm it works now. Thank you!
